name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm i
      - run: npm run build

      - uses: EndBug/add-and-commit@v6
        with:
          branch: main
          message: 'dist: deploy new dist file'
